In [1]:
%matplotlib notebook
%load_ext autoreload
%reload_ext autoreload
%autoreload 2
 
import numpy as np
import os
import matplotlib.pyplot as plt
import matplotlib
import objdet.object_detector

C:\Users\Maria\Anaconda3\lib\site-packages\IPython\kernel\__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
C:\Users\Maria\Anaconda3\lib\site-packages\sklearn\utils\fixes.py:64: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  if 'order' in inspect.getargspec(np.copy)[0]:


In [12]:
def load_dataset(n_samples=30):
    download_dir = r"C:\Users\Maria\Documents\TU Delft\Medical Visualization\Proyecto Clinical Graphics\Object_Detection_in_Medical_Images-2015-11-17\Object Detection in Medical Images\Images"
    boxes = np.load(os.path.join(download_dir, "boxes.npy"))[:n_samples]
    images = []
    for i in range(n_samples):
        image = np.load(os.path.join(download_dir, "image{0:03d}.npy".format(i)))
        images.append(image)
    return boxes, images
boxes, images = load_dataset()

In [3]:
for i, (box, img) in enumerate(zip(boxes, images)):
    # plot image, contour and normal points
    #fig, ax = plt.subplots()
    #fig.suptitle("image {}".format(i))
    #ax.imshow(img.T, cmap=matplotlib.cm.gray)
    #ax.plot(box[:, 0], box[:, 1], "-")
    #ax.set_aspect('equal')
    
    if i == 5:  # use this to stop plotting after the i -th image, or remove to plot all images
        break


In [121]:
select = 30
select_images = images[:select]
select_boxes = boxes[:select]

split = 15
train_images = select_images[:split]
train_boxes = select_boxes[:split]
test_images = select_images[split:]
test_boxes = select_boxes[split:]
 
detector = objdet.object_detector.ObjectDetectorHOG(patch_size=(96, 96), step_size=10, 
                                                    scale_fraction=0.0625, overlap_threshold=0.4,
                                                    orientations=9, pixels_per_cell=(32, 32), 
                                                    cells_per_block=(3, 3))
detector.fit(train_images, train_boxes, debug=False)
predicted_boxes = detector.predict(test_images,debug=False)
mean_score_prob,mean_score_nms = detector.score(test_images, test_boxes) 

patches_coordinates[pick]=
[[[  0  90]
  [ 96  90]
  [ 96 186]
  [  0 186]]]
patches_coordinates[pick]=
[[[ 10 100]
  [106 100]
  [106 196]
  [ 10 196]]]
patches_coordinates[pick]=
[[[  0 110]
  [ 96 110]
  [ 96 206]
  [  0 206]]]
patches_coordinates[pick]=
[[[  0 110]
  [ 96 110]
  [ 96 206]
  [  0 206]]]
patches_coordinates[pick]=
[[[  0 110]
  [ 96 110]
  [ 96 206]
  [  0 206]]]
patches_coordinates[pick]=
[[[  0 110]
  [ 96 110]
  [ 96 206]
  [  0 206]]]
patches_coordinates[pick]=
[[[  0 110]
  [ 96 110]
  [ 96 206]
  [  0 206]]]
patches_coordinates[pick]=
[[[  0 110]
  [ 96 110]
  [ 96 206]
  [  0 206]]]
patches_coordinates[pick]=
[[[ 10 110]
  [106 110]
  [106 206]
  [ 10 206]]]
patches_coordinates[pick]=
[[[ 10 110]
  [106 110]
  [106 206]
  [ 10 206]]]
patches_coordinates[pick]=
[[[ 10 110]
  [106 110]
  [106 206]
  [ 10 206]]]
patches_coordinates[pick]=
[[[ 10 110]
  [106 110]
  [106 206]
  [ 10 206]]]
patches_coordinates[pick]=
[[[ 10 110]
  [106 110]
  [106 206]
  [ 10 206]]]

C:\Users\Maria\Anaconda3\lib\site-packages\sklearn\base.py:175: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  args, varargs, kw, default = inspect.getargspec(init)
C:\Users\Maria\Anaconda3\lib\site-packages\sklearn\base.py:175: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  args, varargs, kw, default = inspect.getargspec(init)
C:\Users\Maria\Anaconda3\lib\site-packages\sklearn\base.py:175: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  args, varargs, kw, default = inspect.getargspec(init)
C:\Users\Maria\Anaconda3\lib\site-packages\sklearn\base.py:175: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  args, varargs, kw, default = inspect.getargspec(init)
C:\Users\Maria\Anaconda3\lib\site-packages\sklearn\base.py:175: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  args, varargs,

In [89]:
print('sfdsaa')

sfdsaa


In [123]:
mean_score_prob

0.56132355117849952

In [105]:
patches=np.array([[[ 0 ,70],  [96 , 70],  [ 96, 166],  [  0 ,166]], [[  0 , 80],  [ 96  ,80],  [ 96,176], [ 0, 176]],[[  0 , 90],  [ 96,  90],  [ 96 ,186],  [  0 ,186]]])
patches[:,0][:,1]


array([70, 80, 90])